[package]
name = "classified"
version = "0.8.0"
entrypoint = "classified.typ"
authors = ["Andrew Benson <abenson+typst@gmail.com>"]
license = "Unlicense"
description = "Report format with support for markings"
repository = "https://github.com/abenson/report"
